version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "6464:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - backend
      - mongodb

  backend:
    image: oven/bun
    working_dir: /app
    volumes:
      - ./:/app
    command: bun run backend/index.js
    environment:
      - ATLAS_URI=mongodb://root:example@mongodb:27017/betting-china?authSource=admin
    networks:
      default:
        aliases:
          - backend
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db

  mongo-compass:
    image: mongocompass/compass
    ports:
      - "4401:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/betting-china?authSource=admin

volumes:
  mongodb_data:
